import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ErrorBoundary } from "@/components/ErrorBoundary";
import { HealthCheckWrapper } from "@/components/HealthCheckWrapper";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// The generated metadata ("Create Next App" / "Generated by create next app")
// was still in place, so every browser tab and bookmark said so.
export const metadata: Metadata = {
  title: {
    default: "FraudGuard Console",
    template: "%s · FraudGuard",
  },
  description:
    "Compliance and fraud-detection console: KYC screening, transaction risk monitoring and alert review.",
  applicationName: "FraudGuard Console",
  robots: { index: false, follow: false }, // an internal tool, never indexed
  icons: { icon: "/favicon.ico" },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b0f19" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ErrorBoundary label="Console">
          <HealthCheckWrapper>{children}</HealthCheckWrapper>
        </ErrorBoundary>
      </body>
    </html>
  );
}
