-- =============================================================================
-- 001 — Core domain tables
--
-- Owns: Users, ToxicityHistory, UserSanctionMatches, Transactions.
--
-- Fixes carried over from the original setup/docker-init.sh:
--   * the Transactions index referenced a column named `timestamp`; the column
--     is `txn_timestamp`, so the CREATE INDEX failed and every transaction
--     lookup was a sequential scan;
--   * every statement is now idempotent (IF NOT EXISTS) instead of dropping
--     and recreating the table, which destroyed data on every re-run.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Users — the KYC record and its standing risk scores
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Users (
    user_id              BIGINT PRIMARY KEY,

    -- Identity
    uin                  CHAR(20),
    uin_hash             CHAR(64),
    username             VARCHAR(100),
    profile_pic          TEXT,
    email                VARCHAR(255),
    phone                VARCHAR(15),
    date_of_birth        TIMESTAMP,
    address              TEXT,
    occupation           VARCHAR(200),
    annual_income        DOUBLE PRECISION,

    -- KYC
    kyc_status           VARCHAR(100),
    kyc_verified_at      TIMESTAMP NULL,
    signature_hash       VARCHAR(64),

    -- Risk
    credit_score         INT,
    current_rps_not      DOUBLE PRECISION,
    current_rps_360      DOUBLE PRECISION,
    last_rps_calculation TIMESTAMP,
    risk_category        VARCHAR(100),

    -- Account status
    blacklisted          BOOLEAN DEFAULT FALSE,
    blacklisted_at       TIMESTAMP NULL,

    -- Pathway bookkeeping (the connector writes these on every upsert)
    version              INT DEFAULT 1,
    time                 BIGINT,
    diff                 INT,

    created_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_age CHECK (
        date_of_birth IS NULL OR EXTRACT(YEAR FROM AGE(date_of_birth)) >= 18
    ),
    CONSTRAINT chk_credit_score CHECK (
        credit_score IS NULL OR credit_score BETWEEN 300 AND 900
    ),
    CONSTRAINT chk_rps_not_range CHECK (
        current_rps_not IS NULL OR current_rps_not BETWEEN 0 AND 1
    ),
    CONSTRAINT chk_rps_360_range CHECK (
        current_rps_360 IS NULL OR current_rps_360 BETWEEN 0 AND 1
    )
);

CREATE INDEX IF NOT EXISTS idx_users_risk_category   ON Users (risk_category);
CREATE INDEX IF NOT EXISTS idx_users_blacklisted     ON Users (blacklisted) WHERE blacklisted;
CREATE INDEX IF NOT EXISTS idx_users_kyc_status      ON Users (kyc_status);
CREATE INDEX IF NOT EXISTS idx_users_rps_not         ON Users (current_rps_not DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_users_last_rps_calc   ON Users (last_rps_calculation NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_users_email           ON Users (email);

COMMENT ON COLUMN Users.current_rps_not IS 'Standing (non-transactional) risk propensity score, 0-1';
COMMENT ON COLUMN Users.current_rps_360 IS 'Latest transaction-derived risk propensity score, 0-1';

-- -----------------------------------------------------------------------------
-- ToxicityHistory — an append-only audit trail of every score change
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ToxicityHistory (
    history_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
    rps_not             DOUBLE PRECISION,
    rps_360             DOUBLE PRECISION,
    sanction_score      DOUBLE PRECISION,
    news_score          DOUBLE PRECISION,
    transaction_score   DOUBLE PRECISION,
    portfolio_score     DOUBLE PRECISION,
    calculated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    calculation_trigger VARCHAR(50),
    time                BIGINT,
    diff                INT
);

CREATE INDEX IF NOT EXISTS idx_user_timeline ON ToxicityHistory (user_id, calculated_at DESC);
CREATE INDEX IF NOT EXISTS idx_toxicity_trigger ON ToxicityHistory (calculation_trigger);

-- -----------------------------------------------------------------------------
-- UserSanctionMatches — the result of every sanctions screening
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS UserSanctionMatches (
    match_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
    match_found         BOOLEAN,
    match_confidence    DOUBLE PRECISION,
    matched_entity_name VARCHAR(500),
    checked_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time                BIGINT,
    diff                INT
);

CREATE INDEX IF NOT EXISTS idx_user_matches ON UserSanctionMatches (user_id, match_found);

-- -----------------------------------------------------------------------------
-- Transactions — the ledger Debezium streams from
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Transactions (
    transaction_id  BIGINT PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
    txn_timestamp   TIMESTAMP,
    amount          DOUBLE PRECISION,
    currency        VARCHAR(10),
    txn_type        VARCHAR(50),
    counterparty_id BIGINT,
    is_fraud        INT DEFAULT 0,

    CONSTRAINT chk_is_fraud CHECK (is_fraud IN (0, 1))
);

-- The original indexed a non-existent column named `timestamp`.
CREATE INDEX IF NOT EXISTS idx_txn_user_time    ON Transactions (user_id, txn_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_txn_counterparty ON Transactions (counterparty_id, txn_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_txn_fraud        ON Transactions (is_fraud) WHERE is_fraud = 1;
CREATE INDEX IF NOT EXISTS idx_txn_timestamp    ON Transactions (txn_timestamp DESC);

-- Debezium's pgoutput plugin needs a replica identity to emit the previous row
-- state; the primary key is sufficient and is the default, stated here so a
-- future schema change cannot silently break change capture.
ALTER TABLE Transactions REPLICA IDENTITY DEFAULT;
ALTER TABLE ToxicityHistory REPLICA IDENTITY DEFAULT;
