-- =============================================================================
-- 003 — compliance_alerts
--
-- The review queue. Written by the mcp-agent flow and by admins through the API.
-- The alert-classification columns (previously a separate ad-hoc migration) are
-- part of the table definition here, because a function in migration 005 depends
-- on `is_true_positive` and failed to create without it.
-- =============================================================================

CREATE TABLE IF NOT EXISTS compliance_alerts (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Subject
    user_id          BIGINT REFERENCES Users(user_id) ON DELETE SET NULL,
    transaction_id   BIGINT,

    -- Classification
    alert_type       VARCHAR(50) NOT NULL,
    severity         VARCHAR(20) NOT NULL DEFAULT 'medium',
    title            VARCHAR(255) NOT NULL,
    description      TEXT,

    -- Context
    entity_id        VARCHAR(100),
    entity_type      VARCHAR(50),
    rps360           DOUBLE PRECISION DEFAULT 0.0,

    -- Workflow
    status           VARCHAR(20) DEFAULT 'active',
    priority         VARCHAR(20) DEFAULT 'medium',
    is_acknowledged  BOOLEAN DEFAULT FALSE,
    acknowledged_at  TIMESTAMP WITHOUT TIME ZONE,
    acknowledged_by  VARCHAR(100),
    dismissal_reason TEXT,

    -- Review outcome — drives the alert hit-rate metric
    is_true_positive BOOLEAN,
    reviewed_at      TIMESTAMP WITHOUT TIME ZONE,
    reviewed_by      VARCHAR(100),

    -- Provenance
    source           VARCHAR(100),
    triggered_by     VARCHAR(100),
    alert_metadata   TEXT,

    created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    time             BIGINT,
    diff             INT,

    CHECK (alert_type IN (
        'kyc_alert', 'transaction_alert', 'fraud_alert', 'aml_alert',
        'sanction_alert', 'behavioral_alert', 'system_alert'
    )),
    CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CHECK (status   IN ('active', 'investigating', 'resolved', 'dismissed', 'escalated')),
    CHECK (priority IN ('low', 'medium', 'high', 'critical'))
);

CREATE INDEX IF NOT EXISTS idx_alerts_user_id          ON compliance_alerts (user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_transaction_id   ON compliance_alerts (transaction_id);
CREATE INDEX IF NOT EXISTS idx_alerts_type             ON compliance_alerts (alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_severity         ON compliance_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status           ON compliance_alerts (status);
CREATE INDEX IF NOT EXISTS idx_alerts_created          ON compliance_alerts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_acknowledged     ON compliance_alerts (is_acknowledged);
CREATE INDEX IF NOT EXISTS idx_alerts_is_true_positive ON compliance_alerts (is_true_positive);
CREATE INDEX IF NOT EXISTS idx_alerts_reviewed_at      ON compliance_alerts (reviewed_at);

-- Composite indexes matching the dashboard's actual queries.
CREATE INDEX IF NOT EXISTS idx_alerts_severity_created ON compliance_alerts (severity DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_user_severity    ON compliance_alerts (user_id, severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status_priority  ON compliance_alerts (status, priority DESC);
-- "Show me everything still open, newest first" is the console's landing query.
CREATE INDEX IF NOT EXISTS idx_alerts_open
    ON compliance_alerts (created_at DESC)
    WHERE status IN ('active', 'investigating');

COMMENT ON COLUMN compliance_alerts.is_true_positive IS
    'TRUE = confirmed, FALSE = false positive, NULL = not yet reviewed';
COMMENT ON COLUMN compliance_alerts.rps360 IS
    'The transaction risk propensity score that triggered the alert, 0-1';
